### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ppap1771** [ppap1771/Face-Recognition#5]
make a GUI/frontend for the application using html, css, Js or Flutter or Django or flask.

**Comment by himanshu17-2000** [comment]
I would want to work on this problem. I'd want to take part in Hacktoberfest. Thank you.

**Comment by ppap1771** [comment]
Sure i am assigning this to you.

**Comment by himanshu17-2000** [comment]
can i use React.js for this  issue ?

**Comment by ppap1771** [comment]
Sure.
